[package]
name = "au"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.18"
rayon = "1.8.1"
regex = "1.10.3"

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "z"
